version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_DB: dbname
    ports:
    - 5432:5432